### ISSUE TITLE
Schema has XML v1.1

### ISSUE THREAD

**Issue by mcapocci** [OCXStandard/OCX_Schema#11]
May I ask why the XML version of the schema is 1.1? This is rare and as I understand it only useful for when the tag names are in non-roman character sets (which I'm assuming will not be the case for OCX).

see e.g. [Here](http://www.ibiblio.org/xml/books/effectivexml/chapters/03.html).

.net, for example, does not support 1.1 and likely never will.

**Comment by ocastrup** [comment]
We use the W3X XML 1.1 Assertion (https://www.w3.org/TR/xmlschema11-1/#cAssertions) 
to restrict the existence of entities in the schema, see the EntityRefBase_T

**Comment by ocastrup** [comment]
We will revert the schema version to XML 1.0 and remove the assert statements. Instead, we plan to use [Schematron ](https://www.schematron.com/)to validate the  XML 1.1 constructs as this is more flexible and powerful.

**Comment by mcapocci** [comment]
Hi,

Seems to be some confusion here between XML v1.1 and XSD v1.1.  The XML version of a schema with version 1.1 can (and mostly should) be 1.0. 

e.g. [here](https://stackoverflow.com/questions/21555511/how-to-indicate-that-an-xml-schema-that-requires-schema-1-1-features).

This issue is about the XML version of the schema being unnecessarily 1.1, not that the schema itself is based on the XSD 1.1 standard. 

So I'm no really bothered if the schema is v1.1, as long as it is expressed in XML v1.0

**Comment by ocastrup** [comment]
Hello,

I believe it has been some nisunderstandings, yes. The 3DOCX XML models does not require XML 1.1 and are XML 1.0 conformant.



Best regards,
Ole Christian

**Comment by ocastrup** [comment]
The misunderstanding has been sorted out as the 3Docx models are XML 1.0 (and not XML 1.1)
