### ISSUE TITLE
Add a Generic Key Value Concept

### ISSUE THREAD

**Issue by ocastrup** [OCXStandard/OCX_Schema#12]
# Motivation 

While a hard schema, where each value has its place, is nice for the basic attributes on entities, 
it makes schema management increasingly difficult for less important values.
E.g. if one wants to preserve the original identifier, add values for additional, but rare business cases.

That's why many standards have the ability to attach attributes using a generic key/value concept.

# Proposal

Add a simple Key / Value concept to EntityBase_T, e.g.

```xml
 <ocxPanel ocx:GUIDRef="...">
    <Properties>
       <Property name="myProperty" value="3443" unit="u2" />

```
Where name and value are mandatory, unit is optional (e.g. material quality)

**Comment by CarstenZerbst** [comment]
See https://github.com/OCXStandard/OCX_Schema/pull/24

**Comment by ocastrup** [comment]
@CarstenZerbst 
Added a CustomProperty type:
```XML
	<xs:element name="CustomProperties" type="ocx:CustomProperties_T">
		<xs:annotation>
			<xs:documentation>Container for custom properties.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="CustomProperties_T">
		<xs:sequence>
			<xs:element ref="ocx:CustomProperty" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="CustomProperty" type="ocx:CustomProperty_T">
		<xs:annotation>
			<xs:documentation>A generic custom property type with a key, value pair and optional unit.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="CustomProperty_T">
		<xs:annotation>
			<xs:documentation>Type definition</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="ocx:Description" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Property  name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="unit" type="xs:IDREF"/>
	</xs:complexType>

```


The CustomProperties is optional and put on all elements inheriting from IdBase:


![Image](https://github.com/OCXStandard/OCX_Schema/assets/44396428/bc3927be-c5ae-44d1-80be-2beb63b898d3)
