### ISSUE TITLE
Suggested change NURBS3D to NURBSCurve

### ISSUE THREAD

**Issue by zooid** [OCXStandard/OCX_Schema#127]
This is so there's consistency.
Since it's NURBSSurface, then it makes more sense to be NURBSCurve instead of NURBS3D which is ambiguous, both NURBS Curve and a NURBS Surface are 3-Dimensional.

Depending on how the Import/Export tool is implemented it could have minor or major impact.

It's an enhancement so, if accepted this change may happen from version 3.0.0+ or 4.0.0+.

**Comment by ocastrup** [comment]
This was discussed at the OCX-IF meeting on 2024.03.21 and it was agreed to not implement the proposal.
