### ISSUE TITLE
Wrong cardinality on PlateCutBy

### ISSUE THREAD

**Issue by ocastrup** [OCXStandard/OCX_Schema#148]
PlateCutBY: Wrong cardinality on a choice of InnerContour and Hole2DContour:  
 
 

![Image](https://github.com/OCXStandard/OCX_Schema/assets/44396428/fceef439-e2f6-455f-842f-ee6cf1148d85)

 
The current definition does not allow for a PlateCutBy with only SlotContour which is a relevant case. 
The Facilitation Team will register an issue on this including removing the surplus sequence model for the SlotContour.

**Comment by ocastrup** [comment]
Changed cardinality on the choice model to allow for CutBy with only SlotContour and no holes:

![image](https://github.com/OCXStandard/OCX_Schema/assets/44396428/31522bd5-a60a-4d42-80d7-3d764b47c0ac)

**Comment by BV-HuguesM** [comment]
@ocastrup Hello, I've just noted the InnerContour became OuterContour. Was it intended?

**Comment by ocastrup** [comment]
> [@ocastrup](https://github.com/ocastrup) Hello, I've just noted the InnerContour became OuterContour. Was it intended?

@BV-HuguesM I will have to check the history of the issue

**Comment by BV-HuguesM** [comment]
@ocastrup Hello, I've checked the history. It's an not-intended change, we decided to keep using the term InnerContour for our test but we did not filled a ticket to make the changes, so we forgot this had to be changed.
I've created the ticket https://github.com/OCXStandard/OCX_Schema/issues/260
