### ISSUE TITLE
Consistancy of BarSection parameters

### ISSUE THREAD

**Issue by BV-HuguesM** [OCXStandard/OCX_Schema#155]
Some parameters differ from a section to a similar one.

- RoundBar having Height and Tube having Diameter

![Image](https://github.com/user-attachments/assets/c4c84570-981d-45ff-a92a-7673f30f8179)
![Image](https://github.com/user-attachments/assets/9810167f-948d-4359-810a-188f5b02c35a)

- Bulb having FlangeWidth and L/I/TBar having Width

![Image](https://github.com/user-attachments/assets/78c3d83c-5621-4b5c-a997-f9f38f74cd04)
![Image](https://github.com/user-attachments/assets/d29bc487-d90e-4249-8972-018c764c361c)

**Comment by ocastrup** [comment]
@BV-HuguesM Mike has registered a proposal for changing the RoundBar property: #157 
I close this issue as it will be resolved from #157
