### ISSUE TITLE
Add Compact Representation of Points

### ISSUE THREAD

**Issue by CarstenZerbst** [OCXStandard/OCX_Schema#20]
# Motivation

The Point3D_T has a definition, which takes a lot of disc space. 
This has a number of downsides, e.g. transfer speed, disc space, and parsing time, ...
Due to the sheer size, some of the real existing models could no longer be opened in a _normal_ editor like Notepad++
or VisualStudioCode at all or in XML mode, exceeding 800 MB.

It could be easily replaced with a more compact representation based on principles already applied in the OCX schema.

# Proposal

Change the definition in the long run to 
```
<xs:complexType name="Point3D_T">
  <xs:annotation>
	  <xs:documentation>Type definition of a point in 3D space composed of X, Y and Z coordinate values.
	  </xs:documentation>
   </xs:annotation>
   <xs:attribute name="coord"  type="ocx:doubleListType" use="required" />
   <xs:attribute name="unit" type="xs:IDREF" use="required">
	<xs:annotation>
		<xs:documentation>The reference to the unitsML reference unit.</xs:documentation>
	</xs:annotation>
</xs:attribute>
```

with a transition phase where either the compact form or the current way is allowed.

### Example Before
```
<ocx:EndPoint>
    <ocx:X numericvalue="36000" unit="u2"/>
    <ocx:Y numericvalue="-7208.6661347532763" unit="u2"/>
    <ocx:Z numericvalue="1200" unit="u2"/>
</ocx:EndPoint>
```
### Example After
```
<ocx:EndPoint coords="36000 -7208.6661347532763 1200 " unit="u2"/>
```

## Pros
I made some simple tests by replacing the current serialization to the compact form and saved ~50 
% of file size without losing any information. If the same change is also applied to similar elements like BoundingBox, ... the effect is even larger

The same method is already applied for knot vectors, so nothing new added to the schema

## Cons
It is no longer possible to set different values to x, y, and z coordinate values. 

## Alternatives

Keep the existing definition at the risk, that files with more detailed geometry is in practice too large and difficult to handle.

**Comment by ocastrup** [comment]
The Point3D definition has been changed to the compact definition as proposed:



![Image](https://github.com/OCXStandard/OCX_Schema/assets/44396428/6214da78-f92b-41c6-9f12-550a01c2e018)

To represent a coordinate position n 2D (typically in the HoleShapeCatalogue) only the X and Y coordinates are necessary. If all three coordinates are given, the third value Z shall be Zero
