### ISSUE TITLE
Add a set of testdata to the ocxwiki

### ISSUE THREAD

**Issue by CarstenZerbst** [OCXStandard/OCX_Schema#22]
# Motivation

The current set of test data is more like a showcase of the capabilities of the OCX standard. 
They do not contain a systematic check on the schema's capability, and a are quite big for automated tests.
To ensure that the implementations of the vendors can interpret the OCX file correctly (at least within the limits intended by the implementor), a common set of test data is needed.

# Proposal

Create a set of test data, where each test file should cover certain aspects and be accompanied by a description of the expected outcome (text, screenshots). 

There is no intention those test data represent a valid vessel design.

These test data could be managed alongside the standard itself to be publically available.

If each vendor creates a set of 5--10 test data, the test data coverage should be quite decent.

### Surface Geometry Test
A test file covering the complete set of geometry primitives used to define a surface with its limiting curve

*ocx:Vessel/ocx:ReferenceSurfaces/ocx:Surface
* ocx:Vessel/ocx:ReferenceSurfaces/ocx:Cone3D
* ...
* ocx:Vessel/ocx:ReferenceSurfaces/ocx:SurfaceCollection

### Panel Geometry Test
* ocx:Vessel/ocx:Panel/ocx:UnboundedGeometry/ocx:Surface
* ...
### Plate Geometry Test
* ocx:Vessel/ocx:Panel/ocx:ComposedOf/ocx:Plate/ocx:UnboundedGeometry
### Stiffener Trace Test
* ocx:Vessel/ocx:Panel/ocx:StiffenedBy/ocx:Stiffener/ocx:Curve3D)

# Alternatives

Keeping the current status is possible.
From my perspective this implies the following risks 

* Lower coverage of the import side
* Fewer tests by the vendors
* Each vendor creates its own test data and thus spends more work

**Comment by ocastrup** [comment]
This is indeed necessary and a task for the upcoming OCX-IF. It has been discussed in the Consortium earlier and I believe all see the benefit of having a maintained test set (unit tests) addressing specific features.

**Comment by ocastrup** [comment]
We acknowledge the proposal. The OCX-IF has decided to develop a test suite to be tested in each test run. The test suite will comprise so-called unit tests addressing specific schema capabilities and larger use cases. The test suite will develop over time but the plan is to have 10-15 unit tests and one large use case.

**Comment by ocastrup** [comment]
Work in progress

**Comment by ocastrup** [comment]
The test models are documented on https://ocxwiki.3docx.org/doku.php?id=ocx-if:testmodels

**Comment by ocastrup** [comment]
The first set of test models has been published on the wiki:
https://ocxwiki.3docx.org/doku.php?id=ocx-if:testmodels
