### ISSUE TITLE
Thickness direction attribute boolean

### ISSUE THREAD

**Issue by zooid** [OCXStandard/OCX_Schema#31]
In 3DEXPERIENCE thickness direction is defined by plate/panel support plane (Reference Plane or Surface) in which a panel/plate lies and with a boolean parameter to invert it.

Could attribute boolean be added to ocx:PlateMaterial element or ocx:Thickness element?
Suggested names of the attribute:
- ThicknessNormalToSupport (default = True)
- ThicknessInverted (default = False)

![image](https://github.com/OCXStandard/OCX_Schema/assets/1837230/f411c4cd-9358-4646-9790-47ce41771ba3)

This is important subsequently when moving to Detail Design model in 3DEXPERIENCE because it defines the thickness compensation.

**Comment by ocastrup** [comment]
The schema do support the material offset by the Offset on the Plate:

![Moulded Offset](https://github.com/OCXStandard/OCX_Schema/assets/44396428/b8897793-d856-415f-84c9-87b0f7ecec9f)

The figure illustrates the offset by 1/2 plate thickness in the normal direction of the moulded surface (UnboundedGeometry). Material offset in opposite direction is given by a negative offset.
