### ISSUE TITLE
Resolve naming confusion between the FrameTables and the VesselGrid

### ISSUE THREAD

**Issue by ocastrup** [OCXStandard/OCX_Schema#36]
The schema FrameTables is a collection of reference grid position (planes) which can be used as limits for any object:

![Image](https://user-images.githubusercontent.com/44396428/258110486-5351ed0c-a048-4135-8145-17d566de697e.png)

The VesselGrid  was introduced later and represents a compact definition of the naval reference system traditionally named as the frame table:

![Image](https://user-images.githubusercontent.com/44396428/258111226-1819d6bf-0c3f-4d06-a178-3554a69b3704.png)

Due to backward compatibility, it was decided at that time to not change the naming but this has created some confusionfor schema implementors. The FrameTables is a concept similar to ReferenceSurfaces and it is proposed to rename FrameTables to ReferenceGrids and at the same time rename VesselGrid to FrameTable (not plural by intention).

**Comment by zooid** [comment]
Hi,

Not trying to be nitpicking but FrameTables->ReferenceGrids and VesselGrid->FrameTable doesn't really solve the confusion issue in my opinion.

By Naval Architecture grid, do you mean Frames, Buttocks, Waterlines?
If so why not just call them that, NavArchRefPlanes->Frames, Buttocks, Waterlines.
Then the structure-related grid could be StrRefPlanes->XRefPlanes, YRefPlanes, ZRefPlanes or Trans/Transverse, Longs/Longitudinals, Decks.

This way there will be no confusion.

Best Regards,
Ivelin Peychev

**Comment by ocastrup** [comment]
The solutions which have been implemented:
1. FrameTables was renamed to ReferencePlanes and moved from CoordinateSystem to Vessel to be aligned with ReferenceSurfaces
2. Unnecessary attributes have been removed from the new ReferencePlanes
3. VesselGrid was renamed to FrameTable
![image](https://github.com/OCXStandard/OCX_Schema/assets/44396428/15d8c68e-d0a1-41e1-9cc4-18183fccb9ab)
