### ISSUE TITLE
Bulb Profile Definition - Flange Width attribute

### ISSUE THREAD

**Issue by odegrand** [OCXStandard/OCX_Schema#7]
In the 2.8.6 version, the _FlangeWidth_ attribute is mandatory:

![Image](https://user-images.githubusercontent.com/122803769/213931594-8c07fc29-db6c-4c2c-b230-17263338b00e.png)

For the time being, there are different interpretations : some CAD solutions export the OCX model with FlangeWidth equal to 0 or generate an OCX file without this FlangeWidth attribute (not conform with the schema).

Proposal: Update the format removing the FlangeWidth attribute for bulb profile.

**Comment by ocastrup** [comment]
Instead of removing the FlangeWidth attribute, can we make it optional?

**Comment by odegrand** [comment]
Yes - I'm Ok to propose this attribute as optional.

**Comment by ocastrup** [comment]
Thanks, this is how it's currently implemented.

Ole Chr.

**Comment by odegrand** [comment]
@ocastrup -> thanks.
When you say " this is how it's currently implemented". In which version of format (the official one and the next released one)?
