### ISSUE TITLE
Cardinality of elements and xs:choice

### ISSUE THREAD

**Issue by mcapocci** [OCXStandard/OCX_Schema#72]
In many places, for example Stiffener_T,  we have used the xs:choice XSD element with some constraints:

![image](https://github.com/OCXStandard/OCX_Schema/assets/122546560/b8ba3bba-fdf6-49e7-a9a9-3f61bf75880d)

Sadly this does not achieve what it set out to do; we can have an unbounded number of any of the child elements, for example CutBy, so the constraint of [0..1] here is bypassed by the use of xs:choice.

The best solution is to revert to the use of xs:sequence - although I understand there are some concerns there - but it should not be difficult to respect the ordering.

Otherwise we will need to add schematron rules, or plain textual notes, although this is suboptimal for those of use who use code generators based on the schema.

**Comment by ocastrup** [comment]
In the OCX-IF meeting on December 1, 2023, we agreed to change the choice model into the sequence model fixing this problem.
