### ISSUE TITLE
Root Point vs Trace Line Definition

### ISSUE THREAD

**Issue by odegrand** [OCXStandard/OCX_Schema#8]
The cross-section origin or root point is defined by the lower left corner of the enclosing bounding box. 

- for T bar, the root point doesn’t correspond to the attached point between the stiffener and the attached plating
- for I-beam / rectangular tube / pipe, the root point doesn’t correspond to the center of gravity of the pillars

![Image](https://user-images.githubusercontent.com/122803769/213931915-b8f20764-3919-4809-8461-8e3e73fcc243.png)

This definition is not "the common one".

We suggest to modify this definition to use the convention used commonly by CAD system -> the attached point of the stiffener with the attached plate.

![Image](https://user-images.githubusercontent.com/122803769/213932007-e3a63a76-384c-445e-8264-7204c85ec712.png)

_Additional reason to modify the root point definition._
For pillar, due to the root point definition, it seems that an inclination definition is mandatory.
In fact, a simple solution for CADs to adapt their trace line to this convention in the export is to set a value to OffsetU and OffsetV using the pipe parameters (Height or Diameter). The local axis are deducted from the Inclination defined in the stiffeners/pillars.

![Image](https://user-images.githubusercontent.com/122803769/213932149-3426d34f-6b4f-4673-8c77-b7848761cf32.png)

If the root point is the same location as the trace line, this issue disappears.

**Comment by ocastrup** [comment]
@odegrand : Nicely documented.

**Comment by odegrand** [comment]
We created this issue to fix first the point about the pipe section. 
In fact, the current schema doesn't work as it is. Due to the definition of the root point and the trace line, the inclination definition is mandatory to define the local coordinate system and then the offset values. In the current schema version, it's not the case.
Therefore, to fix this first point, we propose two options:
1. Modify the schema to put this inclination definition mandatory
2. Modify the document _OCX – Open Class Exchange specification for the Classification of Ships.pdf_ to coincide the root point with the center of gravity the profile only for the pipe section:
![image](https://github.com/OCXStandard/OCX_Schema/assets/122803769/76a049f4-898a-4b5c-9c00-065671b4581c)

**We think that the option 2 is the best one.**

In parallel, according to our different tests, it seems that the convention of the root point vs trace line is not followed by all partners for the import and export sides. Therefore, this point has to be  clarified before to start the first test round.
In my opinion, we can use the existing convention as described in document _OCX – Open Class Exchange specification for the Classification of Ships.pdf_ and each partner must check if this convention is correctly applied if no to apply the modifications accordingly.

**Comment by ocastrup** [comment]
@odegrand : Mike and I have discussed this and we opt for proposal i. and make it mandatory to output the offsets on the SectionRef:


![Image](https://github.com/OCXStandard/OCX_Schema/assets/44396428/945cfd76-f2a4-4103-84ef-ba3a63cb9e52)

We consider this option to be the best as it will be generic and valid and the same for all cross sections. Durin the execution of OCX-IF test round 1 we can ensure that all vendors interpret and implement this in the same way.

**Comment by odegrand** [comment]
@ocastrup, agree with your proposal.
The fact to put these parameters mandatory will bring more attention on them. However, there is no guarantee that all vendors use correctly this convention. This point has to be take into account and check carefully during the OCX-IF tests.

**Comment by ocastrup** [comment]
Noted. Thanks 😊

**Comment by ocastrup** [comment]
Made OffsetU and OffsetV mandatory:
![image](https://github.com/OCXStandard/OCX_Schema/assets/44396428/abb658f1-7061-4134-aa8b-694d91bf2302)
